Reason: fix issue with merge ROIs

diff --git a/main b/main
--- a/main
+++ b/main
@@ -26,21 +26,23 @@ then
 fi
 
 #echo $FREESURFER_LICENSE > license.txt
-time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./create_wm_mask.sh
+if [ ! -f wm_anat.nii.gz ]; then 
+	time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./create_wm_mask.sh
+fi
 
 echo "inflating & generate ROIs"
 time singularity exec -e docker://brainlife/afni:16.3.0 ./roiGeneration.sh
-
-
-if [[ ${INFLATE} == 'null' ]];then
-    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
-else
-    echo "{\"tags\": [\"inflate\" ]}" > product.json
-fi
-
-if [ -z "$(ls -A ./rois/rois/)" ]; then
-    echo "ROI files missing."
-    exit 1
-else
-    exit 0
-fi
+#
+#
+#if [[ ${INFLATE} == 'null' ]];then
+#    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
+#else
+#    echo "{\"tags\": [\"inflate\" ]}" > product.json
+#fi
+#
+#if [ -z "$(ls -A ./rois/rois/)" ]; then
+#    echo "ROI files missing."
+#    exit 1
+#else
+#    exit 0
+#fi
