Update main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -31,27 +31,27 @@ time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt 
 echo "inflating ROIs"
 time singularity exec -e docker://brainlife/afni:16.3.0 ./roiInflate.sh
 
-#echo "roi generation"
-#singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./ROI/roiGeneration
-#
-## Clean up
-#mkdir parc;
-#mkdir rois;
-#mkdir rois/rois;
-#mv parc_inflate_GMI.nii.gz ./parc/parc.nii.gz;
-#mv parc_inflate_GMI.niml.lt ./parc/key.txt;
-#mv *ROI*.nii.gz ./rois/rois/;
-#rm -rf *ROI*.mat *inflate*.niml.lt *.nii.gz;
-#
-#if [[ ${INFLATE} == 'null' ]];then
-#    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
-#else
-#    echo "{\"tags\": [\"inflate\" ]}" > product.json
-#fi
-#
-#if [ -z "$(ls -A ./rois/rois/)" ]; then
-#    echo "ROI files missing."
-#    exit 1
-#else
-#    exit 0
-#fi
+echo "roi generation"
+singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./ROI/roiGeneration
+
+# Clean up
+mkdir parc;
+mkdir rois;
+mkdir rois/rois;
+mv parc_inflate_GMI.nii.gz ./parc/parc.nii.gz;
+mv parc_inflate_GMI.niml.lt ./parc/key.txt;
+mv *ROI*.nii.gz ./rois/rois/;
+rm -rf *ROI*.mat *inflate*.niml.lt *.nii.gz;
+
+if [[ ${INFLATE} == 'null' ]];then
+    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
+else
+    echo "{\"tags\": [\"inflate\" ]}" > product.json
+fi
+
+if [ -z "$(ls -A ./rois/rois/)" ]; then
+    echo "ROI files missing."
+    exit 1
+else
+    exit 0
+fi
