Reason: uncomment bl lines in main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -32,17 +32,17 @@ fi
 
 echo "inflating & generate ROIs"
 time singularity exec -e docker://brainlife/afni:16.3.0 ./roiGeneration.sh
-#
-#
-#if [[ ${INFLATE} == 'null' ]];then
-#    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
-#else
-#    echo "{\"tags\": [\"inflate\" ]}" > product.json
-#fi
-#
-#if [ -z "$(ls -A ./rois/rois/)" ]; then
-#    echo "ROI files missing."
-#    exit 1
-#else
-#    exit 0
-#fi
+
+
+if [[ ${INFLATE} == 'null' ]];then
+    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
+else
+    echo "{\"tags\": [\"inflate\" ]}" > product.json
+fi
+
+if [ -z "$(ls -A ./rois/rois/)" ]; then
+    echo "ROI files missing."
+    exit 1
+else
+    exit 0
+fi
