Reason: Fix issues with freesurfer rois

diff --git a/main b/main
--- a/main
+++ b/main
@@ -7,40 +7,40 @@ inflate=`jq -r '.inflate' config.json`
 mask=`jq -r '.mask' config.json`
 dtiinit=`jq -r '.dtiinit' config.json`
 
-#[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
-#
-#echo "creating masks"
-#if [[ -f ${dtiinit}/dti/bin/brainMask.nii.gz ]];
-#then
-#    cp -v ${dtiinit}/dti/bin/brainMask.nii.gz mask.nii.gz
-#elif [[ ! -f "mask.nii.gz" ]] && [[ ${mask} == 'null' ]];
-#then
-#    time singularity exec -e docker://brainlife/fsl:5.0.9 ./brainmask.sh
-#elif [[ -f "mask.nii.gz" ]];
-#then
-#    echo "brainmask exists. skipping"
-#elif [[ ! ${mask} == 'null' ]];
-#then
-#    echo "brainmask exists. skipping"
-#    cp -v ${mask} mask.nii.gz
-#fi
-#
-#echo $FREESURFER_LICENSE > license.txt
-#time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./create_wm_mask.sh
-#
+[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
+
+echo "creating masks"
+if [[ -f ${dtiinit}/dti/bin/brainMask.nii.gz ]];
+then
+    cp -v ${dtiinit}/dti/bin/brainMask.nii.gz mask.nii.gz
+elif [[ ! -f "mask.nii.gz" ]] && [[ ${mask} == 'null' ]];
+then
+    time singularity exec -e docker://brainlife/fsl:5.0.9 ./brainmask.sh
+elif [[ -f "mask.nii.gz" ]];
+then
+    echo "brainmask exists. skipping"
+elif [[ ! ${mask} == 'null' ]];
+then
+    echo "brainmask exists. skipping"
+    cp -v ${mask} mask.nii.gz
+fi
+
+echo $FREESURFER_LICENSE > license.txt
+time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./create_wm_mask.sh
+
 echo "inflating & generate ROIs"
 time singularity exec -e docker://brainlife/afni:16.3.0 ./roiGeneration.sh
 
 
-#if [[ ${INFLATE} == 'null' ]];then
-#    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
-#else
-#    echo "{\"tags\": [\"inflate\" ]}" > product.json
-#fi
-#
-#if [ -z "$(ls -A ./rois/rois/)" ]; then
-#    echo "ROI files missing."
-#    exit 1
-#else
-#    exit 0
-#fi
+if [[ ${INFLATE} == 'null' ]];then
+    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
+else
+    echo "{\"tags\": [\"inflate\" ]}" > product.json
+fi
+
+if [ -z "$(ls -A ./rois/rois/)" ]; then
+    echo "ROI files missing."
+    exit 1
+else
+    exit 0
+fi
