Update main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -33,17 +33,17 @@ mv parc_inflate_GMI.niml.lt ./parc/key.txt;
 mv *ROI*.nii.gz ./rois/rois/;
 rm -rf *ROI*.mat *inflate*.niml.lt *.nii.gz;
 
-#if [[ ${INFLATE} == 'null' ]];then
-#    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
-#else
-#    echo "{\"tags\": [\"inflate\" ]}" > product.json
-#fi
-#
-#if [ -z "$(ls -A ./rois/rois/)" ]; then
-#    echo "ROI files missing."
-#    exit 1
-#else
-#    exit 0
-#fi
-#
+if [[ ${INFLATE} == 'null' ]];then
+    echo "{\"tags\": [\"no_inflate\" ]}" > product.json
+else
+    echo "{\"tags\": [\"inflate\" ]}" > product.json
+fi
+
+if [ -z "$(ls -A ./rois/rois/)" ]; then
+    echo "ROI files missing."
+    exit 1
+else
+    exit 0
+fi
+
 
